### ISSUE TITLE
Wanted to help make patstrap case.

### ISSUE THREAD

**Issue by fightbaba** [danielfvm/Patstrap#1]
Hellu I'm fightbaba and i'm inspired by your motivation to be headpatted by anime girl (or/and furries) in vrchat
so I'd like to help make a case for Patstrap
Here's what i have in mind at the moment.

Board goal
- Make a portable patstrap model (bettery and stuff)
- Have more torrence design for 3D printing
- Sperate the print into 3 main parts. (head band,ESP case ,battery case)
- The 3 main print will probably be designed to be combined with glue.  
- Will make a variation of non battery version if requested.

badly drawn picture
![400478414_1421259918768181_1232674565301212156_n](https://github.com/danielfvm/Patstrap/assets/115808795/b1c37137-0b39-4181-991d-8f13da34dc2a)

Note :
- on/off switch are missing in the pic due to unsure which case I should put it in, I'll try a few placement first.
- I'm quite new to the DIY/designing thing so please don't expected too much. XD
- I'm working on a 804040 battery version since it's the only battery i have at the moment even it's comicially large.
- The actual component position in the case might be moved/flip while i make the model.
- Please let me know your opinion about my case.

if interested please add/contact me!
Discord : @fightbaba
VRC : fightbaba

**Comment by danielfvm** [comment]
I am so sorry for my late reply. This issue somehow wasn't shown on GitHub's Dashboard ;(
Thank you for your input, I totally agree with your design idea. I like the idea of putting the battery on one side and the ESP on the other as it leaves space for the VR-Headset-Strap.
Personally I use [this](https://amzn.eu/d/drxEmpD) battery with unfortunately much larger dimensions of 50 * 34 * 10 mm, though I will look into the 804040 as it would lead to a smaller design. I also want to add a battery percentage display to the server which would require the necessary wiring. 

I unfortunately have so many projects I want to work on that I haven't worked on this project a lot recently. I will look into investing more time on it and would be glad if you would be interested in helping out.
