### ISSUE TITLE
Mismatched port in DNS SRV record

### ISSUE THREAD

**Issue by ameharoo** [danielfvm/Patstrap#7]
Hi!

I checked yours code and found that. I think need change port in SRV Record to 8888 (currently 80) so that they match.

This will give more flexibility - you will be able to find out the port directly from the DNS record, without hardcoding it in the server code.

**Comment by danielfvm** [comment]
Thanks for pointing that out, back then I used it without knowing how it really works. [Now](https://github.com/danielfvm/Patstrap/commit/8afa7abc3b671c56a9b46637e7439ad129c46126) it should auto discover the ESP port and removed the ESP argument from the server :+1:

**Comment by ameharoo** [comment]
Wow. Thank you!
